In [2]:
#!pip install yfinance

In [1]:
import pandas as pd
import yfinance as yf

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import mean_squared_error

- `yfinance` docs: https://github.com/ranaroussi/yfinance
- What is `SPY`? See here: https://finance.yahoo.com/quote/SPY/

### Get Data

In [2]:
df_spy = yf.download('SPY', start='2024-01-01', end='2024-03-10')

[*********************100%%**********************]  1 of 1 completed

In [3]:
df_spy

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2024-01-02,472.160004,473.670013,470.489990,472.649994,471.186005,123623700
2024-01-03,470.429993,471.190002,468.170013,468.790009,467.337982,103585900
2024-01-04,468.299988,470.959991,467.049988,467.279999,465.832642,84232200
2024-01-05,467.489990,470.440002,466.429993,467.920013,466.470673,86060800
2024-01-08,468.429993,474.750000,468.299988,474.600006,473.129974,74879100
2024-01-09,471.869995,474.929993,471.350006,473.880005,472.412201,65931400
2024-01-10,474.160004,477.450012,473.869995,476.559998,475.083893,67310600
2024-01-11,477.589996,478.119995,472.260010,476.350006,474.874542,77940700
2024-01-12,477.839996,478.600006,475.230011,476.679993,475.203522,57944000
2024-01-16,475.260010,476.609985,473.059998,474.929993,473.458923,85014900
2024-01-17,471.820007,472.790009,469.869995,472.290009,470.827118,68843900
2024-01-18,474.010010,477.059998,472.420013,476.489990,475.014099,91856200
2024-01-19,477.649994,482.720001,476.540009,482.429993,480.935699,110733300
2024-01-22,484.010010,485.220001,482.779999,483.450012,481.952576,75844900
2024-01-23,484.010010,485.109985,482.890015,484.859985,483.358185,49945300
2024-01-24,487.809998,488.769989,484.880005,485.390015,483.886566,81765000
2024-01-25,487.579987,488.309998,485.390015,488.029999,486.518372,72525000
2024-01-26,487.589996,489.119995,486.540009,487.410004,485.900299,76641600
2024-01-29,487.730011,491.420013,487.170013,491.269989,489.748322,61322800
2024-01-30,490.559998,491.619995,490.109985,490.890015,489.369537,58618400
2024-01-31,488.619995,489.079987,482.859985,482.880005,481.384338,126011100
2024-02-01,484.630005,489.230011,483.799988,489.200012,487.684753,91891600
2024-02-02,489.649994,496.049988,489.299988,494.350006,492.818787,99147700
2024-02-05,493.700012,494.380005,490.230011,492.549988,491.024353,75757100
2024-02-06,493.519989,494.320007,492.049988,493.980011,492.449951,55918600
2024-02-07,496.290009,498.529999,495.359985,498.100006,496.557190,70556500
2024-02-08,498.100006,498.709991,497.260010,498.320007,496.776489,52343600
2024-02-09,498.839996,501.649994,498.489990,501.200012,499.647583,63979400
2024-02-12,501.170013,503.500000,500.239990,500.980011,499.428253,56502300
2024-02-13,494.529999,497.089996,490.720001,494.079987,492.549622,113099200
2024-02-14,496.790009,499.070007,494.399994,498.570007,497.025726,68387800
2024-02-15,499.290009,502.200012,498.799988,502.010010,500.455078,61683000
2024-02-16,501.700012,502.869995,498.750000,499.510010,497.962830,75461200
2024-02-20,497.720001,498.410004,494.450012,496.760010,495.221344,71736700
2024-02-21,495.420013,497.369995,493.559998,497.209991,495.669922,59603800
2024-02-22,504.010010,508.489990,503.019989,507.500000,505.928070,76402500
2024-02-23,509.269989,510.130005,507.100006,507.850006,506.276978,61321800
2024-02-26,508.299988,508.750000,505.859985,505.989990,504.422729,50386700
2024-02-27,506.700012,507.160004,504.750000,506.929993,505.359833,48854500
2024-02-28,505.329987,506.859985,504.959991,506.260010,504.691925,56506600
2024-02-29,508.070007,509.739990,505.350006,508.079987,506.506256,83924800
2024-03-01,508.980011,513.289978,508.559998,512.849976,511.261475,76805900
2024-03-04,512.030029,514.200012,512.000000,512.299988,510.713196,49799300
2024-03-05,510.239990,510.700012,504.910004,507.179993,505.609039,72855600
2024-03-06,510.549988,512.070007,508.420013,509.750000,508.171082,68382400
2024-03-07,513.140015,515.890015,509.809998,514.809998,513.215393,58652100
2024-03-08,515.460022,518.219971,511.130005,511.720001,510.134979,86425500

### Modelling # Prediction

In [4]:
# prepare the data
X = np.array(range(len(df_spy))).reshape(-1, 1)  # assuming X is just the time index
y = df_spy['Close'].values  # closing prices as the target

# split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# initialize and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# predict
predictions = model.predict(X_test)

In [5]:
# calculate the MSE for your predictions
mse = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 11.9900225886263

In [6]:
# future indices for 20 business days from March 11 to April 5
future_indices = np.array(range(len(df_spy), len(df_spy) + 20)).reshape(-1, 1)

# using the model to predict future prices
future_predictions = model.predict(future_indices)

# generating dates from March 11 to April 5, 2024 (20 business days)
start_date = pd.Timestamp('2024-03-11')
dates = pd.date_range(start_date, periods=20, freq='B')

# creating the df with the two columns requested in the assignment 
forecast_df = pd.DataFrame({
    'Date': dates,
    'Predicted Closing Value': future_predictions
})

forecast_df

         Date  Predicted Closing Value
0  2024-03-11               515.604281
1  2024-03-12               516.606580
2  2024-03-13               517.608878
3  2024-03-14               518.611176
4  2024-03-15               519.613475
5  2024-03-18               520.615773
6  2024-03-19               521.618071
7  2024-03-20               522.620370
8  2024-03-21               523.622668
9  2024-03-22               524.624967
10 2024-03-25               525.627265
11 2024-03-26               526.629563
12 2024-03-27               527.631862
13 2024-03-28               528.634160
14 2024-03-29               529.636458
15 2024-04-01               530.638757
16 2024-04-02               531.641055
17 2024-04-03               532.643354
18 2024-04-04               533.645652
19 2024-04-05               534.647950

### Save forecast

In [ ]:
firstname = '' # fill in your first name
lastname = '' # fill in your last name
filename = f'{firstname}_{lastname}.csv'

df.forecast.columns = ['date', f'{firstname}_{lastname}']

df_forecast.to_csv(filename, index = 0)

### What to turn in?

- Your Jupyter notebook which builds the model and makes the forecast. (Just for curiosity.)
- A csv file with your forecasts with the following columns   
      - date: dates   
      - firstname_lastname: forecast SPY closing prices