# **Assignment 2**

This assignment focuses on Airbnbs in Berlin, Germany. The goal is to help a company operating small and mid-size apartments hosting 2-6 guests. The company is set to price their new apartments not on the market. This assignment will build a prediction model for prices, and discuss the modeling decisions and compare the results to those of the case study. 

Task
• You may use other variables we used in class.

• You may do different feature engineering depending on the selected environment.

• You may make other sample design decisions!

• In each case, document your steps!

• Have at least 3 different models and compare performance

• Argue for your choice of models
- One model must be theoretically profound linear regression via OLS.
- One model must be Random Forest or any boosting algorithm

In [3]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import os
from pathlib import Path
import sys
from patsy import dmatrices
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.impute import SimpleImputer
from sklearn.inspection import permutation_importance
from sklearn.inspection import PartialDependenceDisplay
from sklearn.inspection import partial_dependence
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_squared_error

In [4]:
# DATA IMPORT - FROM GITHUB
data = pd.read_csv('https://github.com/Iandrewburg/Assignment_1/raw/main/Assignment_2/berlin_airbnb.csv')

In [5]:
data.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,3176.0,https://www.airbnb.com/rooms/3176,2.023120e+13,19/12/2023,previous scrape,Rental unit in Berlin · ★4.63 · 1 bedroom · 2 ...,NaN,The neighbourhood is famous for its variety of...,https://a0.muscache.com/pictures/243355/84afcf...,3718,...,4.69,4.92,4.62,First name and Last name: Nicolas Krotz <br/> ...,f,1,1,0,0,0.84
1,9991.0,https://www.airbnb.com/rooms/9991,2.023120e+13,19/12/2023,city scrape,Rental unit in Berlin · ★5.0 · 4 bedrooms · 7 ...,NaN,Prenzlauer Berg is an amazing neighbourhood wh...,https://a0.muscache.com/pictures/42799131/59c8...,33852,...,5.00,4.86,4.86,03/Z/RA/003410-18,f,1,1,0,0,0.07
2,183988.0,https://www.airbnb.com/rooms/183988,2.023120e+13,19/12/2023,city scrape,Rental unit in Berlin · ★4.69 · 1 bedroom · 2 ...,NaN,NaN,https://a0.muscache.com/pictures/1041e6fd-c369...,882801,...,4.79,4.72,4.62,04/Z/ZA/004232-16,f,1,1,0,0,3.92
3,14325.0,https://www.airbnb.com/rooms/14325,2.023120e+13,19/12/2023,city scrape,Rental unit in Berlin · ★4.68 · Studio · 1 bed...,NaN,NaN,https://a0.muscache.com/pictures/508703/24988a...,55531,...,4.85,4.60,4.45,NaN,f,4,4,0,0,0.16
4,186663.0,https://www.airbnb.com/rooms/186663,2.023120e+13,19/12/2023,city scrape,Rental unit in Berlin · ★4.40 · 1 bedroom · 2 ...,NaN,NaN,https://a0.muscache.com/pictures/1757562/947b4...,897302,...,4.73,4.87,4.00,NaN,f,4,4,0,0,0.11

In [6]:
data.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13327 entries, 0 to 13326
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            13327 non-null  float64
 1   listing_url                                   13327 non-null  object
 2   scrape_id                                     13327 non-null  float64
 3   last_scraped                                  13327 non-null  object
 4   source                                        13327 non-null  object
 5   name                                          13327 non-null  object
 6   description                                   0 non-null      float64
 7   neighborhood_overview                         6867 non-null   object
 8   picture_url                                   13327 non-null  object
 9   host_id                                       13327 non-null  int64
 10  host_url                                      13327 non-null  object
 11  host_name                                     13318 non-null  object
 12  host_since                                    13318 non-null  object
 13  host_location                                 10912 non-null  object
 14  host_about                                    6799 non-null   object
 15  host_response_time                            8275 non-null   object
 16  host_response_rate                            8275 non-null   object
 17  host_acceptance_rate                          9021 non-null   object
 18  host_is_superhost                             13285 non-null  object
 19  host_thumbnail_url                            13318 non-null  object
 20  host_picture_url                              13318 non-null  object
 21  host_neighbourhood                            6385 non-null   object
 22  host_listings_count                           13318 non-null  float64
 23  host_total_listings_count                     13318 non-null  float64
 24  host_verifications                            13318 non-null  object
 25  host_has_profile_pic                          13318 non-null  object
 26  host_identity_verified                        13318 non-null  object
 27  neighbourhood                                 6867 non-null   object
 28  neighbourhood_cleansed                        13327 non-null  object
 29  neighbourhood_group_cleansed                  13327 non-null  object
 30  latitude                                      13327 non-null  float64
 31  longitude                                     13327 non-null  float64
 32  property_type                                 13327 non-null  object
 33  room_type                                     13327 non-null  object
 34  accommodates                                  13327 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                13325 non-null  object
 37  bedrooms                                      0 non-null      float64
 38  beds                                          13119 non-null  float64
 39  amenities                                     13327 non-null  object
 40  price                                         9374 non-null   object
 41  minimum_nights                                13327 non-null  int64
 42  maximum_nights                                13327 non-null  int64
 43  minimum_minimum_nights                        13326 non-null  float64
 44  maximum_minimum_nights                        13326 non-null  float64
 45  minimum_maximum_nights                        13326 non-null  float64
 46  maximum_maximum_nights                        13326 non-null  float64
 47  minimum_nights_avg_ntm                        13326 non-null  float64
 48  maximum_nights_avg_ntm                        13326 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              9374 non-null   object
 51  availability_30                               13327 non-null  int64
 52  availability_60                               13327 non-null  int64
 53  availability_90                               13327 non-null  int64
 54  availability_365                              13327 non-null  int64
 55  calendar_last_scraped                         13327 non-null  object
 56  number_of_reviews                             13327 non-null  int64
 57  number_of_reviews_ltm                         13327 non-null  int64
 58  number_of_reviews_l30d                        13327 non-null  int64
 59  first_review                                  10327 non-null  object
 60  last_review                                   10327 non-null  object
 61  review_scores_rating                          10332 non-null  float64
 62  review_scores_accuracy                        10329 non-null  float64
 63  review_scores_cleanliness                     10331 non-null  float64
 64  review_scores_checkin                         10328 non-null  float64
 65  review_scores_communication                   10331 non-null  float64
 66  review_scores_location                        10328 non-null  float64
 67  review_scores_value                           10326 non-null  float64
 68  license                                       8236 non-null   object
 69  instant_bookable                              13327 non-null  object
 70  calculated_host_listings_count                13327 non-null  int64
 71  calculated_host_listings_count_entire_homes   13327 non-null  int64
 72  calculated_host_listings_count_private_rooms  13327 non-null  int64
 73  calculated_host_listings_count_shared_rooms   13327 non-null  int64
 74  reviews_per_month                             10327 non-null  float64
dtypes: float64(25), int64(15), object(35)
memory usage: 7.6+ MB

In [8]:
data.room_type.value_counts()

room_type
Entire home/apt    8700
Private room       4287
Shared room         208
Hotel room          132
Name: count, dtype: int64

In [9]:
data.property_type.value_counts()

property_type
Entire rental unit             6775
Private room in rental unit    3274
Entire condo                    770
Entire serviced apartment       415
Entire loft                     270
                               ...
Private room in boat              1
Island                            1
Shared room in loft               1
Entire chalet                     1
Casa particular                   1
Name: count, Length: 65, dtype: int64

In [13]:
def airbnb_cleaner(data): 
    
    # filter the data
    data = data[(data.accommodates >= 2) & (data.accommodates <= 6)]
    
    # List of all unique columns for the three models
    columns = list(set(
        ['accommodates', 'beds', 'review_scores_rating', 'host_is_superhost',
         'latitude', 'longitude', 'host_since', 'number_of_reviews',
         'availability_365', 'minimum_nights', 'maximum_nights', 'property_type',
         'room_type', 'beds', 'price']
    ))

    # Creating a new DataFrame with only the selected columns
    data = data[columns]
    
    # clean missing values or 0 values for price
    data = data[data['price'] != 0]
    data = data.dropna(subset=['price'])
    
    # clean up the price column
    data['price'] = data['price'].str.replace('$', '').str.replace(',', '').astype(float).astype(int)
    
    
    # filtering out property_type categories with counts less than 100
    property_type_value_counts = data['property_type'].value_counts()
    to_remove = property_type_value_counts[property_type_value_counts < 100].index
    data = data[~data['property_type'].isin(to_remove)]

    # property type dummies
    property_dummies = pd.get_dummies(data['property_type'], prefix='d_type')
    data = pd.concat([data, property_dummies], axis=1)

    # room type dummies
    room_dummies = pd.get_dummies(data['room_type'], prefix= 'd_room')
    data = pd.concat([data, room_dummies], axis=1)

    data.rename(columns=lambda x: x.replace(" ", "_").lower(), inplace=True)
    
    data = data.rename(columns={
        'review_scores_rating': 'n_review_scores_rating',
        'host_since': 'date_host_start',
        'minimum_nights': 'n_minimum_nights',
        'accommodates': 'n_accommodates',
        'beds': 'n_beds',
        'availability_365': 'n_availability_365',
        'number_of_reviews': 'n_number_of_reviews',
        'maximum_nights': 'n_maximum_nights',
        'room_type': 'f_room_type',
        'property_type': 'f_property_type'
    })
    
    # Convert 'date_host_start' to a date variable
    data['date_host_start'] = pd.to_datetime(data['date_host_start'])

    # Convert 'n_beds' to integer
    data['n_beds'] = data['n_beds'].fillna(0).astype(int)  # Assumes NaN values should be treated as 0

    # Convert 'host_is_superhost' to integer ('t' to 1, 'f' to 0)
    data['host_is_superhost'] = data['host_is_superhost'].map({'t': 1, 'f': 0}).fillna(0).astype(int)  # Assumes NaN values should be treated as 0

    # Convert 'n_review_scores_rating' to int
    data['n_review_scores_rating'] =  data['n_review_scores_rating'].fillna(0)
    

    # changing all dummies to be int
    d_columns = data.columns[data.columns.str.startswith('d_')]
    data[d_columns] = data[d_columns].astype(int)
    
    return data

data = airbnb_cleaner(data)

In [14]:
data.dtypes

f_property_type                               object
n_accommodates                                 int64
n_availability_365                             int64
date_host_start                       datetime64[ns]
longitude                                    float64
n_number_of_reviews                            int64
n_review_scores_rating                       float64
price                                          int32
n_maximum_nights                               int64
latitude                                     float64
f_room_type                                   object
host_is_superhost                              int32
n_minimum_nights                               int64
n_beds                                         int32
d_type_entire_condo                            int32
d_type_entire_home                             int32
d_type_entire_loft                             int32
d_type_entire_rental_unit                      int32
d_type_entire_serviced_apartment               int32
d_type_private_room_in_condo                   int32
d_type_private_room_in_home                    int32
d_type_private_room_in_rental_unit             int32
d_type_room_in_hotel                           int32
d_room_entire_home/apt                         int32
d_room_hotel_room                              int32
d_room_private_room                            int32
dtype: object

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7146 entries, 0 to 13326
Data columns (total 26 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   f_property_type                     7146 non-null   object
 1   n_accommodates                      7146 non-null   int64
 2   n_availability_365                  7146 non-null   int64
 3   date_host_start                     7146 non-null   datetime64[ns]
 4   longitude                           7146 non-null   float64
 5   n_number_of_reviews                 7146 non-null   int64
 6   n_review_scores_rating              7146 non-null   float64
 7   price                               7146 non-null   int32
 8   n_maximum_nights                    7146 non-null   int64
 9   latitude                            7146 non-null   float64
 10  f_room_type                         7146 non-null   object
 11  host_is_superhost                   7146 non-null   int32
 12  n_minimum_nights                    7146 non-null   int64
 13  n_beds                              7146 non-null   int32
 14  d_type_entire_condo                 7146 non-null   int32
 15  d_type_entire_home                  7146 non-null   int32
 16  d_type_entire_loft                  7146 non-null   int32
 17  d_type_entire_rental_unit           7146 non-null   int32
 18  d_type_entire_serviced_apartment    7146 non-null   int32
 19  d_type_private_room_in_condo        7146 non-null   int32
 20  d_type_private_room_in_home         7146 non-null   int32
 21  d_type_private_room_in_rental_unit  7146 non-null   int32
 22  d_type_room_in_hotel                7146 non-null   int32
 23  d_room_entire_home/apt              7146 non-null   int32
 24  d_room_hotel_room                   7146 non-null   int32
 25  d_room_private_room                 7146 non-null   int32
dtypes: datetime64[ns](1), float64(3), int32(15), int64(5), object(2)
memory usage: 1.1+ MB

In [16]:
data.isna().sum().sum()

0

In [17]:
data.shape

(7146, 26)

### EDA

In [14]:
# copy a variable - purpose later, see at variable importance
data['n_accommodates_copy'] = data['n_accommodates']

***numerical variables***

In [15]:
# too long to display and read
data.describe().T

,count,mean,std,min,25%,50%,75%,max
id,11233.0,2.633452e+17,3.936411e+17,3.176000e+03,1.697287e+07,3.842267e+07,6.852340e+17,1.049080e+18
scrape_id,11233.0,2.023120e+13,0.000000e+00,2.023120e+13,2.023120e+13,2.023120e+13,2.023120e+13,2.023120e+13
description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_id,11233.0,1.423954e+08,1.637434e+08,1.581000e+03,1.281804e+07,5.762884e+07,2.434834e+08,5.510794e+08
host_listings_count,11226.0,1.513264e+01,7.138824e+01,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,1.083000e+03
host_total_listings_count,11226.0,1.694539e+01,7.711085e+01,1.000000e+00,1.000000e+00,2.000000e+00,5.000000e+00,1.143000e+03
latitude,11233.0,5.251003e+01,3.284366e-02,5.236904e+01,5.249084e+01,5.250989e+01,5.253233e+01,5.265611e+01
longitude,11233.0,1.340320e+01,6.592717e-02,1.310758e+01,1.336761e+01,1.341224e+01,1.343815e+01,1.371796e+01
accommodates,11233.0,2.921303e+00,1.233958e+00,2.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00
bathrooms,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bedrooms,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
beds,11076.0,1.745215e+00,1.056550e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,9.000000e+00
minimum_nights,11233.0,4.289629e+01,5.321952e+01,1.000000e+00,2.000000e+00,6.000000e+00,9.200000e+01,1.100000e+03
maximum_nights,11233.0,6.261212e+02,4.930788e+02,1.000000e+00,1.120000e+02,3.650000e+02,1.125000e+03,9.999000e+03
minimum_minimum_nights,11232.0,4.286254e+01,5.462927e+01,1.000000e+00,2.000000e+00,5.000000e+00,9.200000e+01,1.100000e+03
maximum_minimum_nights,11232.0,4.933218e+01,6.956276e+01,1.000000e+00,3.000000e+00,7.000000e+00,9.200000e+01,1.100000e+03
minimum_maximum_nights,11232.0,1.339075e+06,5.359622e+07,1.000000e+00,3.500000e+02,1.125000e+03,1.125000e+03,2.147484e+09
maximum_maximum_nights,11232.0,1.339096e+06,5.359622e+07,1.000000e+00,3.650000e+02,1.125000e+03,1.125000e+03,2.147484e+09
minimum_nights_avg_ntm,11232.0,4.847479e+01,6.870205e+01,1.000000e+00,2.100000e+00,6.000000e+00,9.200000e+01,1.100000e+03
maximum_nights_avg_ntm,11232.0,1.339089e+06,5.359622e+07,1.000000e+00,3.650000e+02,1.125000e+03,1.125000e+03,2.147484e+09
calendar_updated,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
availability_30,11233.0,8.855782e+00,1.104515e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,3.000000e+01
availability_60,11233.0,1.997436e+01,2.334455e+01,0.000000e+00,0.000000e+00,5.000000e+00,4.400000e+01,6.000000e+01
availability_90,11233.0,3.161818e+01,3.582085e+01,0.000000e+00,0.000000e+00,1.000000e+01,7.100000e+01,9.000000e+01
availability_365,11233.0,1.168949e+02,1.345329e+02,0.000000e+00,0.000000e+00,4.900000e+01,2.450000e+02,3.650000e+02
number_of_reviews,11233.0,3.801798e+01,8.456161e+01,0.000000e+00,1.000000e+00,7.000000e+00,3.400000e+01,2.363000e+03
number_of_reviews_ltm,11233.0,9.200570e+00,2.075024e+01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+01,7.160000e+02
number_of_reviews_l30d,11233.0,5.833704e-01,1.522860e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.600000e+01
review_scores_rating,8873.0,4.745835e+00,3.863928e-01,0.000000e+00,4.670000e+00,4.860000e+00,5.000000e+00,5.000000e+00
review_scores_accuracy,8871.0,4.790317e+00,3.765962e-01,0.000000e+00,4.750000e+00,4.900000e+00,5.000000e+00,5.000000e+00
review_scores_cleanliness,8873.0,4.680427e+00,4.567074e-01,0.000000e+00,4.570000e+00,4.810000e+00,5.000000e+00,5.000000e+00
review_scores_checkin,8870.0,4.817496e+00,3.654288e-01,0.000000e+00,4.780000e+00,4.920000e+00,5.000000e+00,5.000000e+00
review_scores_communication,8872.0,4.817887e+00,3.844648e-01,0.000000e+00,4.790000e+00,4.930000e+00,5.000000e+00,5.000000e+00
review_scores_location,8870.0,4.761743e+00,3.504845e-01,0.000000e+00,4.670000e+00,4.860000e+00,5.000000e+00,5.000000e+00
review_scores_value,8868.0,4.639337e+00,4.262144e-01,0.000000e+00,4.510000e+00,4.730000e+00,4.890000e+00,5.000000e+00
calculated_host_listings_count,11233.0,9.147868e+00,3.367908e+01,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,2.310000e+02
calculated_host_listings_count_entire_homes,11233.0,8.207959e+00,3.364063e+01,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,2.310000e+02
calculated_host_listings_count_private_rooms,11233.0,6.874388e-01,2.485850e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,6.000000e+01
calculated_host_listings_count_shared_rooms,11233.0,1.766225e-01,2.363503e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.800000e+01
reviews_per_month,8869.0,1.151924e+00,1.863901e+00,1.000000e-02,1.200000e-01,5.000000e-01,1.560000e+00,5.673000e+01
accommodates_copy,11233.0,2.921303e+00,1.233958e+00,2.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00,6.000000e+00

***categorical variables***

In [18]:
data.room_type.value_counts()

room_type
Entire home/apt    7966
Private room       3078
Hotel room          114
Shared room          75
Name: count, dtype: int64

In [19]:
data.property_type.value_counts()

property_type
Entire rental unit                    6237
Private room in rental unit           2301
Entire condo                           722
Entire serviced apartment              358
Entire loft                            247
Room in hotel                          220
Private room in condo                  183
Private room in home                   127
Entire home                            126
Entire guesthouse                       67
Room in boutique hotel                  64
Shared room in hostel                   49
Private room in loft                    45
Entire vacation home                    45
Private room in hostel                  43
Room in aparthotel                      39
Room in serviced apartment              36
Private room in bed and breakfast       32
Private room in townhouse               29
Entire townhouse                        24
Houseboat                               23
Shared room in rental unit              20
Entire bungalow                         18
Entire guest suite                      18
Private room in guesthouse              17
Tiny home                               17
Private room                            14
Private room in serviced apartment      13
Entire place                            12
Private room in pension                 10
Boat                                     7
Entire villa                             7
Private room in tiny home                6
Camper/RV                                6
Private room in vacation home            5
Private room in houseboat                4
Private room in bungalow                 4
Room in hostel                           4
Private room in villa                    4
Private room in casa particular          4
Entire cottage                           3
Shared room in boutique hotel            2
Private room in shipping container       2
Entire cabin                             2
Private room in guest suite              2
Private room in cave                     1
Cave                                     1
Dome                                     1
Shared room in bed and breakfast         1
Shared room in guesthouse                1
Trullo                                   1
Shared room in serviced apartment        1
Private room in boat                     1
Shared room in boat                      1
Bus                                      1
Island                                   1
Entire chalet                            1
Room in bed and breakfast                1
Private room in tipi                     1
Casa particular                          1
Name: count, dtype: int64

In [20]:
data.number_of_reviews.value_counts()

number_of_reviews
0      2364
1       902
2       644
3       507
4       390
       ...
493       1
653       1
655       1
435       1
387       1
Name: count, Length: 456, dtype: int64

In [21]:
data.neighbourhood_cleansed.value_counts()

neighbourhood_cleansed
Alexanderplatz               760
Frankfurter Allee Süd FK     612
Tempelhofer Vorstadt         554
Brunnenstr. Süd              487
Reuterstraße                 393
                            ...
Allende-Viertel                3
MV 1                           3
Neu-Hohenschönhausen Süd       2
Hellersdorf-Süd                1
Neu-Hohenschönhausen Nord      1
Name: count, Length: 136, dtype: int64

***split train and test***
- train is where we do it all, incl CV

- first pick a smaller than usual training set so that models run faster and check if works
- if works, start anew without these two lines

In [22]:
data_train, data_holdout = train_test_split( data, train_size=0.7, random_state=42)

In [23]:
data_train.shape, data_holdout.shape

((7863, 76), (3370, 76))